#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'ControlMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 3

# The Active Message type associated with this message.
AM_TYPE = 75

class ControlMsg(tinyos.message.Message.Message):
    # Create a new ControlMsg of size 3.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=3):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <ControlMsg> \n"
        try:
            s += "  [control_type=0x%x]\n" % (self.get_control_type())
        except:
            pass
        try:
            s += "  [interval=0x%x]\n" % (self.get_interval())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: control_type
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'control_type' is signed (False).
    #
    def isSigned_control_type(self):
        return False
    
    #
    # Return whether the field 'control_type' is an array (False).
    #
    def isArray_control_type(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'control_type'
    #
    def offset_control_type(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'control_type'
    #
    def offsetBits_control_type(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'control_type'
    #
    def get_control_type(self):
        return self.getUIntElement(self.offsetBits_control_type(), 8, 1)
    
    #
    # Set the value of the field 'control_type'
    #
    def set_control_type(self, value):
        self.setUIntElement(self.offsetBits_control_type(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'control_type'
    #
    def size_control_type(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'control_type'
    #
    def sizeBits_control_type(self):
        return 8
    
    #
    # Accessor methods for field: interval
    #   Field type: int
    #   Offset (bits): 8
    #   Size (bits): 16
    #

    #
    # Return whether the field 'interval' is signed (False).
    #
    def isSigned_interval(self):
        return False
    
    #
    # Return whether the field 'interval' is an array (False).
    #
    def isArray_interval(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'interval'
    #
    def offset_interval(self):
        return (8 / 8)
    
    #
    # Return the offset (in bits) of the field 'interval'
    #
    def offsetBits_interval(self):
        return 8
    
    #
    # Return the value (as a int) of the field 'interval'
    #
    def get_interval(self):
        return self.getUIntElement(self.offsetBits_interval(), 16, 1)
    
    #
    # Set the value of the field 'interval'
    #
    def set_interval(self, value):
        self.setUIntElement(self.offsetBits_interval(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'interval'
    #
    def size_interval(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'interval'
    #
    def sizeBits_interval(self):
        return 16
    
