#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'DataMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 14

# The Active Message type associated with this message.
AM_TYPE = 30

class DataMsg(tinyos.message.Message.Message):
    # Create a new DataMsg of size 14.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=14):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <DataMsg> \n"
        try:
            s += "  [nodeid=0x%x]\n" % (self.get_nodeid())
        except:
            pass
        try:
            s += "  [temperature=0x%x]\n" % (self.get_temperature())
        except:
            pass
        try:
            s += "  [humidity=0x%x]\n" % (self.get_humidity())
        except:
            pass
        try:
            s += "  [illumination=0x%x]\n" % (self.get_illumination())
        except:
            pass
        try:
            s += "  [timestamp=0x%x]\n" % (self.get_timestamp())
        except:
            pass
        try:
            s += "  [sequence_num=0x%x]\n" % (self.get_sequence_num())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: nodeid
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'nodeid' is signed (False).
    #
    def isSigned_nodeid(self):
        return False
    
    #
    # Return whether the field 'nodeid' is an array (False).
    #
    def isArray_nodeid(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'nodeid'
    #
    def offset_nodeid(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'nodeid'
    #
    def offsetBits_nodeid(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'nodeid'
    #
    def get_nodeid(self):
        return self.getUIntElement(self.offsetBits_nodeid(), 16, 1)
    
    #
    # Set the value of the field 'nodeid'
    #
    def set_nodeid(self, value):
        self.setUIntElement(self.offsetBits_nodeid(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'nodeid'
    #
    def size_nodeid(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'nodeid'
    #
    def sizeBits_nodeid(self):
        return 16
    
    #
    # Accessor methods for field: temperature
    #   Field type: int
    #   Offset (bits): 16
    #   Size (bits): 16
    #

    #
    # Return whether the field 'temperature' is signed (False).
    #
    def isSigned_temperature(self):
        return False
    
    #
    # Return whether the field 'temperature' is an array (False).
    #
    def isArray_temperature(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'temperature'
    #
    def offset_temperature(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'temperature'
    #
    def offsetBits_temperature(self):
        return 16
    
    #
    # Return the value (as a int) of the field 'temperature'
    #
    def get_temperature(self):
        return self.getUIntElement(self.offsetBits_temperature(), 16, 1)
    
    #
    # Set the value of the field 'temperature'
    #
    def set_temperature(self, value):
        self.setUIntElement(self.offsetBits_temperature(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'temperature'
    #
    def size_temperature(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'temperature'
    #
    def sizeBits_temperature(self):
        return 16
    
    #
    # Accessor methods for field: humidity
    #   Field type: int
    #   Offset (bits): 32
    #   Size (bits): 16
    #

    #
    # Return whether the field 'humidity' is signed (False).
    #
    def isSigned_humidity(self):
        return False
    
    #
    # Return whether the field 'humidity' is an array (False).
    #
    def isArray_humidity(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'humidity'
    #
    def offset_humidity(self):
        return (32 / 8)
    
    #
    # Return the offset (in bits) of the field 'humidity'
    #
    def offsetBits_humidity(self):
        return 32
    
    #
    # Return the value (as a int) of the field 'humidity'
    #
    def get_humidity(self):
        return self.getUIntElement(self.offsetBits_humidity(), 16, 1)
    
    #
    # Set the value of the field 'humidity'
    #
    def set_humidity(self, value):
        self.setUIntElement(self.offsetBits_humidity(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'humidity'
    #
    def size_humidity(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'humidity'
    #
    def sizeBits_humidity(self):
        return 16
    
    #
    # Accessor methods for field: illumination
    #   Field type: int
    #   Offset (bits): 48
    #   Size (bits): 16
    #

    #
    # Return whether the field 'illumination' is signed (False).
    #
    def isSigned_illumination(self):
        return False
    
    #
    # Return whether the field 'illumination' is an array (False).
    #
    def isArray_illumination(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'illumination'
    #
    def offset_illumination(self):
        return (48 / 8)
    
    #
    # Return the offset (in bits) of the field 'illumination'
    #
    def offsetBits_illumination(self):
        return 48
    
    #
    # Return the value (as a int) of the field 'illumination'
    #
    def get_illumination(self):
        return self.getUIntElement(self.offsetBits_illumination(), 16, 1)
    
    #
    # Set the value of the field 'illumination'
    #
    def set_illumination(self, value):
        self.setUIntElement(self.offsetBits_illumination(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'illumination'
    #
    def size_illumination(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'illumination'
    #
    def sizeBits_illumination(self):
        return 16
    
    #
    # Accessor methods for field: timestamp
    #   Field type: long
    #   Offset (bits): 64
    #   Size (bits): 32
    #

    #
    # Return whether the field 'timestamp' is signed (False).
    #
    def isSigned_timestamp(self):
        return False
    
    #
    # Return whether the field 'timestamp' is an array (False).
    #
    def isArray_timestamp(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'timestamp'
    #
    def offset_timestamp(self):
        return (64 / 8)
    
    #
    # Return the offset (in bits) of the field 'timestamp'
    #
    def offsetBits_timestamp(self):
        return 64
    
    #
    # Return the value (as a long) of the field 'timestamp'
    #
    def get_timestamp(self):
        return self.getUIntElement(self.offsetBits_timestamp(), 32, 1)
    
    #
    # Set the value of the field 'timestamp'
    #
    def set_timestamp(self, value):
        self.setUIntElement(self.offsetBits_timestamp(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'timestamp'
    #
    def size_timestamp(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'timestamp'
    #
    def sizeBits_timestamp(self):
        return 32
    
    #
    # Accessor methods for field: sequence_num
    #   Field type: int
    #   Offset (bits): 96
    #   Size (bits): 16
    #

    #
    # Return whether the field 'sequence_num' is signed (False).
    #
    def isSigned_sequence_num(self):
        return False
    
    #
    # Return whether the field 'sequence_num' is an array (False).
    #
    def isArray_sequence_num(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'sequence_num'
    #
    def offset_sequence_num(self):
        return (96 / 8)
    
    #
    # Return the offset (in bits) of the field 'sequence_num'
    #
    def offsetBits_sequence_num(self):
        return 96
    
    #
    # Return the value (as a int) of the field 'sequence_num'
    #
    def get_sequence_num(self):
        return self.getUIntElement(self.offsetBits_sequence_num(), 16, 1)
    
    #
    # Set the value of the field 'sequence_num'
    #
    def set_sequence_num(self, value):
        self.setUIntElement(self.offsetBits_sequence_num(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'sequence_num'
    #
    def size_sequence_num(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'sequence_num'
    #
    def sizeBits_sequence_num(self):
        return 16
    
